name: CD Docker Deploy

on:
  push:
    branches: [ main ]
# jobs:
#   Deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - name: Deploy in EC2
#         env:
#             PRIVATE_KEY: ${{ secrets.AWS_NodeServer_PRIVATE_KEY  }}
#             ADDRESS : ${{ secrets.ADDRESS  }}
#             USER_NAME : ec2-user
#         run: |
#           echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
#           ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${ADDRESS} '
#             docker compose pull && docker compose up -d
#           '
jobs:
  deploy:
    name: Upload to Amazon ec2
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Configure Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::580347531117:role/SSM_king
        aws-region: us-east-1
    - name: Deploy
      run: |
       aws ssm send-command \
    --instance-ids "i-0faeec2d56a87c751" \
    --comment "deployment script" \
    --parameters commands=sh deploy.sh \
    --output text