name: CD Docker Deploy

on:
  push:
    branches: [ main ]
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy in EC2
        env:
            PRIVATE_KEY: ${{ secrets.AWS_NodeServer_PRIVATE_KEY  }}
            ADDRESS : ${{ secrets.ADDRESS  }}
            USER_NAME : ec2-user
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${ADDRESS} '
            docker compose pull && docker compose up -d
          '