name: Docker Image CI
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '12.x'

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          username: mitchell5790

      - name: Build the Python Image
        working-directory: /home/runner/work/zenabyss/zenabyss/pythonServer
        run:  docker build --tag mitchell5790/zenabyss:python_server .
      - name: install
        working-directory: /home/runner/work/zenabyss/zenabyss/nodeServer
        run: npm install
      - name: build and compile node
        working-directory: /home/runner/work/zenabyss/zenabyss/nodeServer
        run: npm run build
      - name: Build the Node Image
        working-directory: /home/runner/work/zenabyss/zenabyss/nodeServer
        run: docker build --tag mitchell5790/zenabyss:node_server .

      - name: push Python Image
        working-directory: /home/runner/work/zenabyss/zenabyss/pythonServer
        run: docker push  mitchell5790/zenabyss:python_server

      - name: push Node Image
        working-directory: /home/runner/work/zenabyss/zenabyss/nodeServer
        run: docker push  mitchell5790/zenabyss:node_server

  deploy:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9']

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install aws cli
      run: |
        python -m pip install --upgrade pip
        pip install awscli

    - name: configure env
      run: |
        aws configure set aws_access_key_id  ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set region us-east-1

    - name: deploy script
      run:  aws ssm send-command --instance-ids "i-0faeec2d56a87c751"   --document-name "AWS-RunShellScript"     --comment "deployment script"     --parameters commands='["sh /home/ssm-user/deploy.sh"]'   --output text