name: Docker Image CI
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        username: mitchell5790
    - name: Build the Python Image
      working-directory: /home/runner/work/zenabyss/zenabyss/pythonServer
      run:  docker build --tag mitchell5790/zenabyss:python_server .

    - name: Build the Node Image
      working-directory: /home/runner/work/zenabyss/zenabyss/nodeServer
      run: docker build --tag mitchell5790/zenabyss:node_server .

    - name: push Python Image
      working-directory: /home/runner/work/zenabyss/zenabyss/pythonServer
      run: docker push  mitchell5790/zenabyss:python_server

    - name: push Node Image
      working-directory: /home/runner/work/zenabyss/zenabyss/nodeServer
      run: docker push  mitchell5790/zenabyss:node_server

  deploy:
    name: "deploy to docker"
    permissions:
      contents: read
      id-token: write
    needs: build

    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: "Configure AWS credentials from Production account"
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-west-2
          role-to-assume: "arn:aws:iam::580347531117:role/SSM_king"
      -
        name: "deploy script"
        run:  |
          aws ssm send-command \
          --instance-ids "i-0faeec2d56a87c751" \
          --document-name "AWS-RunShellScript" \
          --comment "IP config" \
          --parameters "commands=sh ~/ssm-user/deploy.sh"