name: CD Docker Deploy
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    name: "deploy to docker"
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: "Configure AWS credentials from Production account"
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-west-2
          role-to-assume: "arn:aws:iam::580347531117:role/SSM_king"
      -
        name: "deploy script"
        run:  |
          aws ssm send-command \
          --instance-ids "i-0faeec2d56a87c751" \
          --document-name "AWS-RunShellScript" \
          --comment "IP config" \
          --parameters "commands=sh ~/ssm-user/deploy.sh"