name: Docker Image CI
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Python Image
      with:
      password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      username: mitchell5790
      working-directory: /home/runner/work/zenabyss/zenabyss/pythonServer
      run:  docker build --tag mitchell5790/zenabyss:python_server .

    - name: Build the Node Image
      working-directory: /home/runner/work/zenabyss/zenabyss/nodeServer
      run: docker build --tag mitchell5790/zenabyss:node_server .

    - name: push Python Image
      working-directory: /home/runner/work/zenabyss/zenabyss/pythonServer
      run: docker push  mitchell5790/zenabyss:python_server

    - name: push Node Image
      working-directory: /home/runner/work/zenabyss/zenabyss/nodeServer
      run: docker push  mitchell5790/zenabyss:node_server