name: zenabyss

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
- uses: actions/setup-python@v4
  with:
    python-version: ['3.9']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      working-directory: ./pythonServer
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      working-directory: ./pythonServer
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      working-directory: ./pythonServer
      run: pytest -q ./py_test/*
